<Project>

  <PropertyGroup>
    <BaseOutputPath>$(MSBuildThisFileDirectory)../build/backend/bin/</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)../build/backend/obj/</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
  </PropertyGroup>

</Project>
